version: '3.7'
services:

    frontend:
      image: app-frontend
      build: ./frontend 
      ports:
        - "5000:3000"
      networks:
        - app-network

    backend:
      image: app-backend
      build: ./backend 
      ports:
        - "8000:8000"
      networks:
        - app-network
        - db

    appdb:
      image: mysql:8.0
      command: --default-authentication-plugin=mysql_native_password
      volumes:
        - ./initdb:/docker-entrypoint-initdb.d
      environment:
        - MYSQL_ROOT_PASSWORD=root
        - MYSQL_DATABASE=laravel
        - MYSQL_USER=user
        - MYSQL_PASSWORD=password
      ports:
        - 3307:3306
      networks:
        - db

    phpmyadmin:
      image: phpmyadmin/phpmyadmin
      environment:
        - PMA_HOST=appdb
        - PMA_PORT=3306
      depends_on:
        - appdb
      ports:
        - 8443:80
      networks:
        - db

networks:
  app-network:
  db:
